import { config } from "dotenv"
config();


const { PORT, NODE_ENV, POSTGRES_DATABASE_URL, REDIS_DATABASE_URI, JWT_SECRET, JWT_REFRESH_SECRET, ACCESS_TOKEN_EXPIRY, REFRESH_TOKEN_EXPIRY, APP_URL,
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
    GOOGLE_CALLBACK_URL,
    CLIENT_URL,
    R2_ACCOUNT_ID,
    R2_ACCESS_KEY,
    R2_SECRET_KEY,
    R2_BUCKET,
    RESEND_API,
    VERIFIED_DOMAIN,
    R2_PUBLIC_URL,
    COLLAB_SERVICE_PORT,
    COLLAB_SERVICE_NAME,
    AUTO_SAVE_INTERVAL_MS,
    CONVERTER_SERVICE_URL,
    RATE_LIMIT_ENABLED
} = process.env;



export const _config = {
    PORT: PORT,
    NODE_ENV,
    POSTGRES_DATABASE_URL,
    REDIS_DATABASE_URI,
    JWT_SECRET,
    JWT_REFRESH_SECRET,
    ACCESS_TOKEN_EXPIRY,
    REFRESH_TOKEN_EXPIRY,
    APP_URL,
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
    GOOGLE_CALLBACK_URL,
    CLIENT_URL,
    R2_ACCOUNT_ID,
    R2_ACCESS_KEY,
    R2_SECRET_KEY,
    R2_BUCKET,
    RESEND_API,
    VERIFIED_DOMAIN,
    R2_PUBLIC_URL,
    COLLAB_SERVICE_PORT,
    COLLAB_SERVICE_NAME,
    AUTO_SAVE_INTERVAL_MS: AUTO_SAVE_INTERVAL_MS ? parseInt(AUTO_SAVE_INTERVAL_MS) : 15 * 60 * 1000,// default 15 mins
    CONVERTER_SERVICE_URL,
    RATE_LIMIT_ENABLED: RATE_LIMIT_ENABLED === 'true'
}